
checks:
  argument-count:
    enabled: true
  complex-logic:
    enabled: true
  file-lines:
    enabled: true
  method-complexity:
    enabled: true
  method-count:
    enabled: true
  method-lines:
    enabled: false # rubocop checks this
  nested-control-flow:
    enabled: true
  return-statements:
    enabled: true
  similar-code:
    enabled: true
    exclude_patterns:
      - 'spec/**/*_spec.rb'
  identical-code:
    enabled: true

plugins:
  brakeman:
    enabled: false
  bundler-audit:
    enabled: false
  flog:
    enabled: true
    exclude_patterns:
      - 'spec/'
  reek:
    enabled: true
    exclude_patterns:
      - 'spec/'
  rubocop:
    enabled: true
    channel: rubocop-0-60
    config:
      file: .rubocop.codeclimate.yml

exclude_patterns:
  - 'config/'
  - 'db/'
  - 'app/assets/plugins/'
  - 'app/assets/reader/'
  - 'app/assets/images/'
  - 'features/'
  - 'frontend/'
  - 'public/'
  - '**/node_modules/'
  - 'script/'
  - '**/test/'
  - '**/tests/'
  - '**/vendor/'