---
detectors:
  IrresponsibleModule:
    enabled: false

  UtilityFunction:
    public_methods_only: true

  DuplicateMethodCall:
    allow_calls:
      - 'Rails.env'

  UncommunicativeModuleName:
    accept:
      - 'V5'

directories:
  'app/helpers':
    UtilityFunction:
      enabled: false
    FeatureEnvy:
      enabled: false

  'app/workers':
    UtilityFunction:
      enabled: false

  'app/controllers':
    InstanceVariableAssumption:
      enabled: false
  'app/mailers':
    InstanceVariableAssumption:
      enabled: false