env:
  global:
    - CC_TEST_REPORTER_ID=caa26723a5be994043d1a250f744379813f7c59a85ff03e78a4d3121a568a544
language: ruby
rvm:
 - 2.5.3
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
services:
  - postgresql
script:
  - bundle exec rubocop
  - bundle exec reek
  - bin/rails test
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT