default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: photofeedapp_db_1

test:
  <<: *default
  database: travis_ci_test

production:
  <<: *default
  encoding: utf8
  database: ENV['PROD_DB']
  username: ENV['DB_USER']
  password: ENV['DB_PASS']
  host: ENV['DB_HOST']
  port: ENV['DB_PORT']
